version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: contract-assessment-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contract_assessment_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contract-assessment-backend
    restart: no
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/contract_assessment_db
      JWT_SECRET: your-super-secret-key-change-in-production
      PORT: 5000
      NODE_ENV: production
    # Add healthcheck to ensure database is ready before starting the app
    healthcheck:
      test: ["CMD", "npx", "prisma", "migrate", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contract-assessment-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api

volumes:
  postgres-data:
